services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: raremanuscripts_db
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10

  main-app:
    build: ./main-app
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/raremanuscripts_db
      DB_USERNAME: root
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}
      DIGITIZATION_SERVICE_URL: ${DIGITIZATION_SERVICE_URL}
      REDIS_HOST: redis
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
      SPRING_PROFILES_ACTIVE: prod
      EMAIL_SERVICE_URL: ${EMAIL_SERVICE_URL}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    ports:
      - "8080:8080"

  digitization-service:
    build: ./digitization-service
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/digitization_db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8081:8081"

  frontend:
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - main-app
    ports:
      - "80:80"
  email-service:
    build:
      context: ./email-service
      dockerfile: Dockerfile

    container_name: email-service

    ports:
      - "3001:3001"

    environment:
      PORT: 3001
      FRONTEND_URL: ${FRONTEND_URL}
      GMAIL_USER: ${GMAIL_USER}
      GMAIL_APP_PASSWORD: ${GMAIL_APP_PASSWORD}

    restart: unless-stopped

volumes:
  mysql-data: