spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate

logging.level.io.github.cdimascio=WARN
logging.level.me.paulschwarz=WARN
logging.level.org.hibernate.SQL=WARN

logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR

spring.datasource.url=jdbc:postgresql://db.qjkrazxdjingtvlxpbqy.supabase.co:5432/postgres?sslmode=require